apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-gateway.fullname" . }}-declarative
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
data:
  kong.yml: |
{{- include "api-gateway.kongDeclarative" . | nindent 4 }}
