apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.fullname" . }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: proxy
      port: {{ .Values.service.proxyPort }}
      targetPort: proxy
      protocol: TCP
    {{- if .Values.admin.enabled }}
    - name: admin
      port: {{ .Values.admin.port }}
      targetPort: admin
      protocol: TCP
    {{- end }}
  selector:
    {{- include "api-gateway.selectorLabels" . | nindent 4 }}
