replicaCount: 2

image:
  repository: ghcr.io/nasibashop/order-service
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8081"
  sidecar.istio.io/inject: "true"

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  fsGroup: 10001

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false

service:
  type: ClusterIP
  httpPort: 8081

env:
  orderServicePort: "8081"
  kafkaBrokers: kafka.infrastructure.svc.cluster.local:9092

secrets:
  existingSecret: order-service-secrets
  databaseUrlKey: ORDER_SERVICE_DATABASE_URL
  databaseUserKey: ORDER_SERVICE_DATABASE_USER
  databasePasswordKey: ORDER_SERVICE_DATABASE_PASSWORD

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

probes:
  liveness:
    path: /actuator/health/liveness
    initialDelaySeconds: 40
    periodSeconds: 20
  readiness:
    path: /actuator/health/readiness
    initialDelaySeconds: 20
    periodSeconds: 10

nodeSelector: {}
tolerations: []
affinity: {}
