apiVersion: v1
kind: Service
metadata:
  name: {{ include "media-service.fullname" . }}
  labels:
    {{- include "media-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "media-service.selectorLabels" . | nindent 4 }}
